package com.agenda.model;
// Generated 19-abr-2015 21:47:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="agenda"
)
public class Persona  implements java.io.Serializable {


     private Integer personaId;
     private String nombre;
     private String apellido;
     private String mail;
     private Integer user = 0;
     private String login;
     private String pwd;
     private Set tareas = new HashSet(0);

    public Persona() {
    }

    //Constructor add persona-login

    public Persona(Integer personaId, String nombre, String apellido, String mail, Integer user, String login, String pwd) {
        this.personaId = personaId;
        this.nombre = nombre;
        this.apellido = apellido;
        this.mail = mail;
        this.user = user;
        this.login = login;
        this.pwd = pwd;
    }
    
	
    public Persona(String nombre, String apellido, String mail) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.mail = mail;
    }
    public Persona(String nombre, String apellido, String mail, Set tareas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.mail = mail;
       this.tareas = tareas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="persona_id", unique=true, nullable=false)
    public Integer getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }

    
    @Column(name="nombre", nullable=false, length=65)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=65)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="mail", nullable=false, length=45)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name = "user", nullable = false,length = 4)
    public Integer getUser() {
        return user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    
    @Column(name = "login", nullable = true,length = 25)
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name = "pwd",nullable = true, length = 256)
    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


